version: "3.8"

services:
  two-share:
    image: ghcr.io/mindwerk-ai/two-share:main
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
    volumes:
      - twoshare-data:/opt/app/backend/data
      - twoshare-images:/opt/app/frontend/public/img

volumes:
  twoshare-data:
  twoshare-images:
